name: Publish
run-name: Publish library to GitHub Packages.
on: [ push ]
#  push:
#    branches:
#      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: '17'
      - uses: gradle/gradle-build-action@v3
        with:
          gradle-version: wrapper
          cache-read-only: false
      - name: Setup config
        run: cp .github/workflows/local.properties local.properties
      - name: Publish
        run: ./gradlew clean publish
        env:
          GITHUB_ACTOR: ${{ secrets.PUBLISH_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
