name: CI
run-name: "CI on #${{ github.ref_name }} @${{ github.actor }}"
on:
  push:
    branches-ignore:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v4
        with:
          gradle-version: wrapper
      - name: Run test
        run: ./gradlew test --rerun-tasks --continue
      - if: success() || failure()
        uses: actions/upload-artifact@v4
        name: Upload test report
        with:
          name: "reports_${{ github.run_id }}"
          path: build/reports/tests
