name: CI
run-name: "CI on #${{ github.ref_name }} @${{ github.actor }}"
on:
  push:
    branches-ignore:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: wrapper
      - name: Setup config
        run: cp .github/workflows/local.properties local.properties
      - name: Prepare DB
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: docker-compose.yml
          down-flags: --volumes
      - name: Run test
        run: ./gradlew test --rerun-tasks --continue
        env:
          GITHUB_ACTOR: ${{ secrets.PUBLISH_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
      - if: success() || failure()
        uses: actions/upload-artifact@v4
        name: Upload test report
        with:
          name: "reports_${{ github.run_id }}"
          path: build/reports/tests
